package br.ufpe.cin.android.recyclerview

object Constants {

    val professores = arrayOf(
        Professor("Leopoldo", "lmt"),
        Professor("Henrique", "hemr"),
        Professor("Castor", "fjclf"),
        Professor("Paulo", "phmb"),
        Professor("Sergio", "scbs")
    )

    val maisProfessores = arrayOf(
        Professor("Leopoldo", "lmt"),
        Professor("Paulo", "phmb"),
        Professor("Castor", "fjclf"),
        Professor("Henrique", "hemr"),
        Professor("Sergio", "scbs"),
        Professor("Marcelo", "damorim"),
        Professor("Kiev", "kiev"),
        Professor("Vinicius", "vcg"),
        Professor("Juliano", "jmi"),
        Professor("Alexandre", "acm"),
        Professor("Marcio", "mlc2"),
        Professor("Gustavo", "ghpc"),
        Professor("Leopoldo", "lmt"),
        Professor("Paulo", "phmb"),
        Professor("Castor", "fjclf"),
        Professor("Henrique", "hemr"),
        Professor("Sergio", "scbs"),
        Professor("Marcelo", "damorim"),
        Professor("Kiev", "kiev"),
        Professor("Vinicius", "vcg"),
        Professor("Juliano", "jmi"),
        Professor("Alexandre", "acm"),
        Professor("Marcio", "mlc2"),
        Professor("Gustavo", "ghpc"),
        Professor("Leopoldo", "lmt"),
        Professor("Paulo", "phmb"),
        Professor("Castor", "fjclf"),
        Professor("Henrique", "hemr"),
        Professor("Sergio", "scbs"),
        Professor("Marcelo", "damorim"),
        Professor("Kiev", "kiev"),
        Professor("Vinicius", "vcg"),
        Professor("Juliano", "jmi"),
        Professor("Alexandre", "acm"),
        Professor("Marcio", "mlc2"),
        Professor("Gustavo", "ghpc"),
        Professor("Leopoldo", "lmt"),
        Professor("Paulo", "phmb"),
        Professor("Castor", "fjclf"),
        Professor("Henrique", "hemr"),
        Professor("Sergio", "scbs"),
        Professor("Marcelo", "damorim"),
        Professor("Kiev", "kiev"),
        Professor("Vinicius", "vcg"),
        Professor("Juliano", "jmi"),
        Professor("Alexandre", "acm"),
        Professor("Marcio", "mlc2"),
        Professor("Gustavo", "ghpc"),
        Professor("Leopoldo", "lmt"),
        Professor("Paulo", "phmb"),
        Professor("Castor", "fjclf"),
        Professor("Henrique", "hemr"),
        Professor("Sergio", "scbs"),
        Professor("Marcelo", "damorim"),
        Professor("Kiev", "kiev"),
        Professor("Vinicius", "vcg"),
        Professor("Juliano", "jmi"),
        Professor("Alexandre", "acm"),
        Professor("Marcio", "mlc2"),
        Professor("Gustavo", "ghpc"),
        Professor("Leopoldo", "lmt"),
        Professor("Paulo", "phmb"),
        Professor("Castor", "fjclf"),
        Professor("Henrique", "hemr"),
        Professor("Sergio", "scbs"),
        Professor("Marcelo", "damorim"),
        Professor("Kiev", "kiev"),
        Professor("Vinicius", "vcg"),
        Professor("Juliano", "jmi"),
        Professor("Alexandre", "acm"),
        Professor("Marcio", "mlc2"),
        Professor("Gustavo", "ghpc"),
        Professor("Leopoldo", "lmt"),
        Professor("Paulo", "phmb"),
        Professor("Castor", "fjclf"),
        Professor("Henrique", "hemr"),
        Professor("Sergio", "scbs"),
        Professor("Marcelo", "damorim"),
        Professor("Kiev", "kiev"),
        Professor("Vinicius", "vcg"),
        Professor("Juliano", "jmi"),
        Professor("Alexandre", "acm"),
        Professor("Marcio", "mlc2"),
        Professor("Gustavo", "ghpc"),
        Professor("Augusto", "acas")
    )


}